# Generated by Django 5.0.6 on 2025-07-29 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('topico', models.CharField(blank=True, max_length=255, null=True)),
                ('quiz_data', models.JSONField(blank=True, help_text='Dados do quiz: perguntas, opções e respostas.', null=True)),
                ('placa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudos_educativos', to='zonas.placa')),
            ],
        ),
    ]
