# Generated by Django 5.0.6 on 2025-07-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo_educativo', '0001_initial'),
        ('zonas', '0007_alter_subzona_geometria_alter_zona_geometria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudoeducativo',
            name='placa',
        ),
        migrations.AddField(
            model_name='conteudoeducativo',
            name='placa',
            field=models.ManyToManyField(blank=True, related_name='conteudos_educativos', to='zonas.placa'),
        ),
    ]
