# Generated by Django 5.0.6 on 2025-07-27 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo_educativo', '0001_initial'),
        ('zonas', '0008_qrcode_qr_code_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudoeducativo',
            name='ponto_interesse',
        ),
        migrations.RemoveField(
            model_name='conteudoeducativo',
            name='zona',
        ),
        migrations.AddField(
            model_name='conteudoeducativo',
            name='placa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudos_educativos', to='zonas.placa'),
        ),
    ]
