# Generated by Django 5.0.6 on 2025-07-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo_educativo', '0002_remove_conteudoeducativo_ponto_interesse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoeducativo',
            name='quiz_data',
            field=models.JSONField(blank=True, help_text='Dados do quiz: perguntas, opções e respostas.', null=True),
        ),
    ]
