CREATE TABLE "gestores_ambientais" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar UNIQUE NOT NULL,
  "tipo" varchar,
  "estado" varchar(2) DEFAULT 'PE',
  "status_contrato" varchar
);

CREATE TABLE "usuarios_gestores" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer UNIQUE NOT NULL,
  "gestor_ambiental_id" integer NOT NULL,
  "cargo" varchar
);

CREATE TABLE "relatorios_gestao" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gestor_ambiental_id" integer NOT NULL,
  "tipo_relatorio" varchar NOT NULL,
  "data_geracao" timestamp DEFAULT (now()),
  "dados_json" jsonb
);

CREATE TABLE "usuarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo_perfil" varchar NOT NULL DEFAULT 'Turista',
  "email" varchar UNIQUE,
  "senha_hash" varchar,
  "criado_em" timestamp DEFAULT (now())
);

CREATE TABLE "zonas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "descricao" text,
  "regras" text,
  "restrita" boolean DEFAULT false,
  "geometria" "geometry(Polygon,4326)" NOT NULL
);

CREATE TABLE "pontos_de_interesse" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "descricao" text,
  "latitude" decimal(10,8) NOT NULL,
  "longitude" decimal(11,8) NOT NULL,
  "tipo" varchar,
  "zona_id" integer
);

CREATE TABLE "placas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zona_id" integer NOT NULL,
  "codigo_qr" varchar UNIQUE NOT NULL,
  "descricao" text,
  "atividades_autorizadas" jsonb,
  "latitude" double,
  "longitude" double
);

CREATE TABLE "acessos_qr" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "placa_id" integer NOT NULL,
  "usuario_id" integer,
  "timestamp_acesso" timestamp DEFAULT (now()),
  "latitude_dispositivo" decimal(10,8),
  "longitude_dispositivo" decimal(11,8),
  "info_dispositivo" varchar
);

CREATE TABLE "historico_acesso_zonas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "zona_id" integer NOT NULL,
  "timestamp" timestamp DEFAULT (now()),
  "via_qrcode" boolean DEFAULT false
);

CREATE TABLE "historico_localizacao" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "timestamp_localizacao" timestamp NOT NULL DEFAULT (now()),
  "coordenadas" "geometry(Point,4326)" NOT NULL
);

CREATE TABLE "logs_acesso_zona_restrita" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer NOT NULL,
  "zona_id" integer NOT NULL,
  "timestamp_entrada" timestamp NOT NULL DEFAULT (now()),
  "coordenada_entrada" "geometry(Point,4326)",
  "notificacao_enviada" boolean DEFAULT false
);

CREATE TABLE "feedbacks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer,
  "ponto_interesse_id" integer,
  "tipo_feedback" varchar NOT NULL,
  "mensagem" text NOT NULL,
  "status" varchar DEFAULT 'Recebido',
  "criado_em" timestamp DEFAULT (now())
);

CREATE TABLE "usuarios_pontos_favoritos" (
  "usuario_id" integer NOT NULL,
  "ponto_interesse_id" integer NOT NULL,
  "criado_em" timestamp DEFAULT (now()),
  PRIMARY KEY ("usuario_id", "ponto_interesse_id")
);

CREATE TABLE "conteudos_educativos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar NOT NULL,
  "tipo" varchar NOT NULL,
  "conteudo" text NOT NULL,
  "topico" varchar,
  "ponto_interesse_id" integer,
  "zona_id" integer
);

CREATE TABLE "comunidades_locais" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "descricao" text,
  "localizacao_base" "geometry(Point,4326)",
  "contato_email" varchar
);

CREATE TABLE "roteiros_turisticos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "descricao" text,
  "comunidade_id" integer,
  "tipo" varchar
);

CREATE TABLE "roteiros_pontos_interesse" (
  "roteiro_id" integer NOT NULL,
  "ponto_interesse_id" integer NOT NULL,
  "ordem" integer,
  PRIMARY KEY ("roteiro_id", "ponto_interesse_id")
);

CREATE TABLE "parceiros_b2b" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer UNIQUE NOT NULL,
  "nome_negocio" varchar NOT NULL,
  "cnpj" varchar(14) UNIQUE,
  "categoria" varchar
);

CREATE TABLE "produtos_marketplace" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parceiro_b2b_id" integer,
  "comunidade_id" integer,
  "nome" varchar NOT NULL,
  "descricao" text,
  "preco" decimal(10,2) NOT NULL,
  "ativo" boolean DEFAULT true
);

CREATE TABLE "transacoes_marketplace" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "produto_id" integer NOT NULL,
  "comprador_usuario_id" integer NOT NULL,
  "data_transacao" timestamp DEFAULT (now()),
  "valor_total" decimal(10,2) NOT NULL,
  "status_pagamento" varchar DEFAULT 'Pendente',
  "comissao_plataforma" decimal(10,2)
);

CREATE TABLE "boletins_balneabilidade" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ponto_interesse_id" integer NOT NULL,
  "data_emissao" date NOT NULL,
  "status" varchar NOT NULL,
  "fonte" varchar DEFAULT 'CPRH'
);

CREATE TABLE "interacoes_ia" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer,
  "timestamp_interacao" timestamp DEFAULT (now()),
  "pergunta" text,
  "resposta_gerada" text,
  "contexto_localizacao" "geometry(Point,4326)",
  "avaliacao_utilidade" integer
);

CREATE TABLE "perfil_turista_analytics" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer UNIQUE NOT NULL,
  "origem_cidade" varchar,
  "origem_pais" varchar DEFAULT 'Brasil',
  "interesses_declarados" jsonb,
  "total_acessos_qr" integer DEFAULT 0,
  "zonas_mais_visitadas" jsonb
);

CREATE UNIQUE INDEX ON "boletins_balneabilidade" ("ponto_interesse_id", "data_emissao");

COMMENT ON TABLE "gestores_ambientais" IS 'Acesso apenas a relatórios agregados.';

COMMENT ON TABLE "usuarios_gestores" IS 'Vínculo técnico. Sem acesso a conteúdos nem marketplace.';

COMMENT ON TABLE "relatorios_gestao" IS 'Fonte de dados agregados: acessos, fluxos, zonas restritas.';

COMMENT ON TABLE "usuarios" IS 'Usuários acessam zonas, locais, conteúdos e marketplace.';

COMMENT ON TABLE "zonas" IS 'Acessadas por usuários via QR Code ou plataforma. Dados agregados vão para relatórios.';

COMMENT ON TABLE "pontos_de_interesse" IS 'Exibido ao usuário ao escolher uma zona.';

COMMENT ON TABLE "placas" IS 'QR Codes físicos acessados por usuários. Iniciam o fluxo.';

COMMENT ON TABLE "acessos_qr" IS 'Usado para mapas de calor. Relatórios mostram contagem agregada.';

COMMENT ON TABLE "historico_acesso_zonas" IS 'Acesso a zonas via QR ou app. Alimenta fluxo.';

COMMENT ON TABLE "historico_localizacao" IS 'Movimento dos usuários. Dados anonimizados para relatórios.';

COMMENT ON TABLE "logs_acesso_zona_restrita" IS 'Usado em alertas e segurança. Visível em relatórios agregados.';

COMMENT ON TABLE "feedbacks" IS 'Não visível para gestores.';

COMMENT ON TABLE "conteudos_educativos" IS 'Exibido após usuário acessar zona e local. Gestores não acessam.';

COMMENT ON TABLE "boletins_balneabilidade" IS 'Disponível para gestores e usuários.';

COMMENT ON TABLE "perfil_turista_analytics" IS 'Dados usados em IA e agregados em relatórios.';

ALTER TABLE "usuarios_gestores" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "usuarios_gestores" ADD FOREIGN KEY ("gestor_ambiental_id") REFERENCES "gestores_ambientais" ("id");

ALTER TABLE "relatorios_gestao" ADD FOREIGN KEY ("gestor_ambiental_id") REFERENCES "gestores_ambientais" ("id");

ALTER TABLE "pontos_de_interesse" ADD FOREIGN KEY ("zona_id") REFERENCES "zonas" ("id");

ALTER TABLE "placas" ADD FOREIGN KEY ("ponto_interesse_id") REFERENCES "pontos_de_interesse" ("id");

ALTER TABLE "acessos_qr" ADD FOREIGN KEY ("placa_id") REFERENCES "placas" ("id");

ALTER TABLE "acessos_qr" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "historico_acesso_zonas" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "historico_acesso_zonas" ADD FOREIGN KEY ("zona_id") REFERENCES "zonas" ("id");

ALTER TABLE "historico_localizacao" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "logs_acesso_zona_restrita" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "logs_acesso_zona_restrita" ADD FOREIGN KEY ("zona_id") REFERENCES "zonas" ("id");

ALTER TABLE "feedbacks" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "feedbacks" ADD FOREIGN KEY ("ponto_interesse_id") REFERENCES "pontos_de_interesse" ("id");

ALTER TABLE "usuarios_pontos_favoritos" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "usuarios_pontos_favoritos" ADD FOREIGN KEY ("ponto_interesse_id") REFERENCES "pontos_de_interesse" ("id");

CREATE TABLE "pontos_de_interesse_conteudos_educativos" (
  "pontos_de_interesse_id" integer,
  "conteudos_educativos_ponto_interesse_id" integer,
  PRIMARY KEY ("pontos_de_interesse_id", "conteudos_educativos_ponto_interesse_id")
);

ALTER TABLE "pontos_de_interesse_conteudos_educativos" ADD FOREIGN KEY ("pontos_de_interesse_id") REFERENCES "pontos_de_interesse" ("id");

ALTER TABLE "pontos_de_interesse_conteudos_educativos" ADD FOREIGN KEY ("conteudos_educativos_ponto_interesse_id") REFERENCES "conteudos_educativos" ("ponto_interesse_id");


CREATE TABLE "zonas_conteudos_educativos" (
  "zonas_id" integer,
  "conteudos_educativos_zona_id" integer,
  PRIMARY KEY ("zonas_id", "conteudos_educativos_zona_id")
);

ALTER TABLE "zonas_conteudos_educativos" ADD FOREIGN KEY ("zonas_id") REFERENCES "zonas" ("id");

ALTER TABLE "zonas_conteudos_educativos" ADD FOREIGN KEY ("conteudos_educativos_zona_id") REFERENCES "conteudos_educativos" ("zona_id");


ALTER TABLE "roteiros_turisticos" ADD FOREIGN KEY ("comunidade_id") REFERENCES "comunidades_locais" ("id");

ALTER TABLE "roteiros_pontos_interesse" ADD FOREIGN KEY ("roteiro_id") REFERENCES "roteiros_turisticos" ("id");

ALTER TABLE "roteiros_pontos_interesse" ADD FOREIGN KEY ("ponto_interesse_id") REFERENCES "pontos_de_interesse" ("id");

ALTER TABLE "parceiros_b2b" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

CREATE TABLE "parceiros_b2b_produtos_marketplace" (
  "parceiros_b2b_id" integer,
  "produtos_marketplace_parceiro_b2b_id" integer,
  PRIMARY KEY ("parceiros_b2b_id", "produtos_marketplace_parceiro_b2b_id")
);

ALTER TABLE "parceiros_b2b_produtos_marketplace" ADD FOREIGN KEY ("parceiros_b2b_id") REFERENCES "parceiros_b2b" ("id");

ALTER TABLE "parceiros_b2b_produtos_marketplace" ADD FOREIGN KEY ("produtos_marketplace_parceiro_b2b_id") REFERENCES "produtos_marketplace" ("parceiro_b2b_id");


CREATE TABLE "comunidades_locais_produtos_marketplace" (
  "comunidades_locais_id" integer,
  "produtos_marketplace_comunidade_id" integer,
  PRIMARY KEY ("comunidades_locais_id", "produtos_marketplace_comunidade_id")
);

ALTER TABLE "comunidades_locais_produtos_marketplace" ADD FOREIGN KEY ("comunidades_locais_id") REFERENCES "comunidades_locais" ("id");

ALTER TABLE "comunidades_locais_produtos_marketplace" ADD FOREIGN KEY ("produtos_marketplace_comunidade_id") REFERENCES "produtos_marketplace" ("comunidade_id");


ALTER TABLE "transacoes_marketplace" ADD FOREIGN KEY ("produto_id") REFERENCES "produtos_marketplace" ("id");

ALTER TABLE "transacoes_marketplace" ADD FOREIGN KEY ("comprador_usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "boletins_balneabilidade" ADD FOREIGN KEY ("ponto_interesse_id") REFERENCES "pontos_de_interesse" ("id");

ALTER TABLE "interacoes_ia" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "perfil_turista_analytics" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");
