-- Tipos de Usuário
CREATE TABLE "tipos_usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descricao" varchar NOT NULL
);

-- Usuários
CREATE TABLE "usuarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "senha_hash" varchar NOT NULL,
  "tipo_usuario_id" integer NOT NULL
);

ALTER TABLE "usuarios" ADD FOREIGN KEY ("tipo_usuario_id") REFERENCES "tipos_usuario" ("id");

-- Zonas Geográficas
CREATE TABLE "zonas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "descricao" text,
  "latitude" double,
  "longitude" double,
  "restrita" boolean DEFAULT false
);

-- Pontos de Interesse
CREATE TABLE "pontos_de_interesse" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zona_id" integer,
  "nome" varchar NOT NULL,
  "descricao" text,
  "latitude" double,
  "longitude" double
);

ALTER TABLE "pontos_de_interesse" ADD FOREIGN KEY ("zona_id") REFERENCES "zonas" ("id");

-- Placas
CREATE TABLE "placas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zona_id" integer NOT NULL,
  "codigo_qr" varchar UNIQUE NOT NULL,
  "descricao" text,
  "atividades_autorizadas" jsonb,
  "latitude" double,
  "longitude" double
);

ALTER TABLE "placas" ADD FOREIGN KEY ("zona_id") REFERENCES "zonas" ("id");

-- Atividades padronizadas (opcional mas recomendada)
CREATE TABLE "atividades" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar UNIQUE NOT NULL
);

-- Relacionamento muitos para muitos entre placas e atividades
CREATE TABLE "placas_atividades" (
  "placa_id" integer,
  "atividade_id" integer,
  PRIMARY KEY ("placa_id", "atividade_id")
);

ALTER TABLE "placas_atividades" ADD FOREIGN KEY ("placa_id") REFERENCES "placas" ("id");
ALTER TABLE "placas_atividades" ADD FOREIGN KEY ("atividade_id") REFERENCES "atividades" ("id");

-- Conteúdos Educativos
CREATE TABLE "conteudos_educativos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar NOT NULL,
  "descricao" text,
  "link" varchar,
  "tipo" varchar
);

-- Relacionamento com pontos de interesse
CREATE TABLE "pontos_de_interesse_conteudos_educativos" (
  "ponto_interesse_id" integer,
  "conteudo_educativo_id" integer,
  PRIMARY KEY ("ponto_interesse_id", "conteudo_educativo_id")
);

ALTER TABLE "pontos_de_interesse_conteudos_educativos"
  ADD FOREIGN KEY ("ponto_interesse_id") REFERENCES "pontos_de_interesse" ("id");
ALTER TABLE "pontos_de_interesse_conteudos_educativos"
  ADD FOREIGN KEY ("conteudo_educativo_id") REFERENCES "conteudos_educativos" ("id");

-- Históricos de Localização
CREATE TABLE "historico_localizacao" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer,
  "zona_id" integer,
  "data_hora" timestamp DEFAULT CURRENT_TIMESTAMP,
  "latitude" double,
  "longitude" double
);

ALTER TABLE "historico_localizacao" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");
ALTER TABLE "historico_localizacao" ADD FOREIGN KEY ("zona_id") REFERENCES "zonas" ("id");

-- Logs de Acesso a Zonas Restritas
CREATE TABLE "logs_acesso_zonas_restritas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer,
  "zona_id" integer,
  "data_hora" timestamp DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "logs_acesso_zonas_restritas" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");
ALTER TABLE "logs_acesso_zonas_restritas" ADD FOREIGN KEY ("zona_id") REFERENCES "zonas" ("id");

-- Notificações
CREATE TABLE "notificacoes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" integer,
  "mensagem" text,
  "data_hora" timestamp DEFAULT CURRENT_TIMESTAMP,
  "tipo" varchar
);

ALTER TABLE "notificacoes" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

-- Marketplace
CREATE TABLE "produtos_servicos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "descricao" text,
  "preco" double,
  "tipo" varchar,
  "disponibilidade" boolean DEFAULT true
);

CREATE TABLE "comunidades_parceiras" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "descricao" text,
  "contato" varchar
);

CREATE TABLE "produtos_comunidade" (
  "comunidade_id" integer,
  "produto_servico_id" integer,
  PRIMARY KEY ("comunidade_id", "produto_servico_id")
);

ALTER TABLE "produtos_comunidade" ADD FOREIGN KEY ("comunidade_id") REFERENCES "comunidades_parceiras" ("id");
ALTER TABLE "produtos_comunidade" ADD FOREIGN KEY ("produto_servico_id") REFERENCES "produtos_servicos" ("id");

-- Mapas de Calor
CREATE TABLE "mapas_calor" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zona_id" integer,
  "dados" jsonb,
  "data" date
);

ALTER TABLE "mapas_calor" ADD FOREIGN KEY ("zona_id") REFERENCES "zonas" ("id");

-- Comentários explicativos
COMMENT ON TABLE "usuarios" IS 'Gestores ambientais têm acesso a relatórios agregados. Parceiros B2B e comunidades acessam marketplace. Usuários turísticos acessam via QR Code ou web.';
COMMENT ON TABLE "logs_acesso_zonas_restritas" IS 'Acesso às zonas restritas é monitorado apenas por gestores ambientais.';
COMMENT ON TABLE "mapas_calor" IS 'Dados agregados de presença de usuários por zona.';
