# Generated by Django 5.0.6 on 2025-07-29 05:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletimBalneabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('fonte', models.CharField(default='CPRH', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_feedback', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(default='Recebido', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GestorAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(default='PE', max_length=2)),
                ('status_contrato', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAcessoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('via_qrcode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_localizacao', models.DateTimeField(auto_now_add=True)),
                ('coordenadas', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='InteracaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_interacao', models.DateTimeField(auto_now_add=True)),
                ('pergunta', models.TextField(blank=True, null=True)),
                ('resposta_gerada', models.TextField(blank=True, null=True)),
                ('contexto_localizacao', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('avaliacao_utilidade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogAcessoZonaRestrita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_entrada', models.DateTimeField(auto_now_add=True)),
                ('coordenada_entrada', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('notificacao_enviada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilTuristaAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('origem_pais', models.CharField(default='Brasil', max_length=255)),
                ('interesses_declarados', models.JSONField(blank=True, null=True)),
                ('total_acessos_qr', models.IntegerField(default=0)),
                ('zonas_mais_visitadas', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioGestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relatorio', models.CharField(max_length=255)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('dados_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPontoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcessoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_acesso', models.DateTimeField(auto_now_add=True)),
                ('latitude_dispositivo', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude_dispositivo', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('info_dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='zonas.qrcode')),
            ],
        ),
    ]
