# Generated by Django 5.0.6 on 2025-07-29 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relatorios', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('zonas', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoqr',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='boletimbalneabilidade',
            name='ponto_interesse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.pontodeinteresse'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ponto_interesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonas.pontodeinteresse'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='historicoacessozona',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='historicoacessozona',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.zona'),
        ),
        migrations.AddField(
            model_name='historicolocalizacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='interacaoia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='logacessozonarestrita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='logacessozonarestrita',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.zona'),
        ),
        migrations.AddField(
            model_name='perfilturistaanalytics',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='relatoriogestao',
            name='gestor_ambiental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.gestorambiental'),
        ),
        migrations.AddField(
            model_name='usuariogestor',
            name='gestor_ambiental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.gestorambiental'),
        ),
        migrations.AddField(
            model_name='usuariogestor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='usuariopontofavorito',
            name='ponto_interesse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.pontodeinteresse'),
        ),
        migrations.AddField(
            model_name='usuariopontofavorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='boletimbalneabilidade',
            unique_together={('ponto_interesse', 'data_emissao')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariopontofavorito',
            unique_together={('usuario', 'ponto_interesse')},
        ),
    ]
