# Generated by Django 5.0.6 on 2025-07-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_initial'),
        ('zonas', '0005_qrcode_remove_placa_codigo_qr_placa_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acessoqr',
            name='placa',
        ),
        migrations.AddField(
            model_name='acessoqr',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='zonas.qrcode'),
        ),
    ]
