# Generated by Django 5.0.6 on 2025-07-29 05:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='O código único do QR Code.', max_length=255, unique=True)),
                ('qr_code_value', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Valor único para o QR Code físico.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('regras', models.TextField(blank=True, null=True)),
                ('restrita', models.BooleanField(default=False)),
                ('geometria', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PontoDeInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontos_de_interesse', to='zonas.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('acesso_restrito', models.BooleanField(default=False, help_text='Indica se o acesso a esta placa é restrito.')),
                ('num_embarcacoes_desembarque', models.IntegerField(blank=True, help_text='Número de embarcações permitidas para embarque/desembarque.', null=True)),
                ('max_pessoas_catamara', models.IntegerField(blank=True, help_text='Número máximo de pessoas por catamarã.', null=True)),
                ('max_pessoas_miudas', models.IntegerField(blank=True, help_text='Número máximo de pessoas para embarcações miúdas.', null=True)),
                ('atividades_autorizadas', models.JSONField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ponto_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placas', to='zonas.pontodeinteresse')),
                ('qr_code', models.OneToOneField(blank=True, help_text='O QR Code associado a esta placa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placa', to='zonas.qrcode')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placas', to='zonas.zona')),
            ],
        ),
        migrations.CreateModel(
            name='PlacaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.atividade')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.placa')),
            ],
            options={
                'unique_together': {('placa', 'atividade')},
            },
        ),
    ]
