# Generated by Django 5.0.6 on 2025-07-29 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placa',
            name='zona',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='regras',
        ),
        migrations.CreateModel(
            name='Subzona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subzonas', to='zonas.zona')),
            ],
        ),
        migrations.AddField(
            model_name='placa',
            name='subzona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placas', to='zonas.subzona'),
        ),
    ]
