# Generated by Django 5.0.6 on 2025-07-27 00:01

from django.contrib.gis.geos import Polygon
from django.db import migrations
from django.contrib.gis.db import models as gis_models

def set_default_geometria(apps, schema_editor):
    Zona = apps.get_model('zonas', 'Zona')
    # Define um polígono padrão (ex: um pequeno quadrado em uma coordenada arbitrária)
    # Você pode ajustar este valor para um polígono que faça sentido para o seu contexto.
    # Exemplo: um pequeno quadrado em (0,0)
    default_polygon = Polygon(((0.0, 0.0), (0.0, 0.0001), (0.0001, 0.0001), (0.0001, 0.0), (0.0, 0.0)))
    
    # Atualiza todas as Zonas onde geometria é NULL
    Zona.objects.filter(geometria__isnull=True).update(geometria=default_polygon)

class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0002_alter_zona_geometria'),
    ]

    operations = [
        migrations.RunPython(set_default_geometria, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='zona',
            name='geometria',
            field=gis_models.PolygonField(srid=4326),
        ),
    ]
