# Generated by Django 5.0.6 on 2025-07-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0002_remove_placa_zona_remove_zona_regras_subzona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subzona',
            name='atividades_permitidas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subzona',
            name='atividades_proibidas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
