# Generated by Django 5.0.6 on 2025-07-29 05:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0003_subzona_atividades_permitidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subzona',
            name='geometria',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
