# Generated by Django 5.0.6 on 2025-07-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0004_alter_zona_geometria'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='O código único do QR Code.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='placa',
            name='codigo_qr',
        ),
        migrations.AddField(
            model_name='placa',
            name='qr_code',
            field=models.OneToOneField(blank=True, help_text='O QR Code associado a esta placa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placa', to='zonas.qrcode'),
        ),
    ]
