# Generated by Django 5.0.6 on 2025-07-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0004_subzona_geometria'),
    ]

    operations = [
        migrations.AddField(
            model_name='placa',
            name='localidade_x',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placa',
            name='nome_placa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
