# Generated by Django 5.0.6 on 2025-07-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0005_qrcode_remove_placa_codigo_qr_placa_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='placa',
            name='acesso_restrito',
            field=models.BooleanField(default=False, help_text='Indica se o acesso a esta placa é restrito.'),
        ),
    ]
