# Generated by Django 5.0.6 on 2025-07-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0005_placa_localidade_x_placa_nome_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa',
            name='atividades_autorizadas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
