# Generated by Django 5.0.6 on 2025-07-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0006_placa_acesso_restrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='placa',
            name='max_pessoas_catamara',
            field=models.IntegerField(blank=True, help_text='Número máximo de pessoas por catamarã.', null=True),
        ),
        migrations.AddField(
            model_name='placa',
            name='max_pessoas_miudas',
            field=models.IntegerField(blank=True, help_text='Número máximo de pessoas para embarcações miúdas.', null=True),
        ),
        migrations.AddField(
            model_name='placa',
            name='num_embarcacoes_desembarque',
            field=models.IntegerField(blank=True, help_text='Número de embarcações permitidas para embarque/desembarque.', null=True),
        ),
    ]
