# Generated by Django 5.0.6 on 2025-07-29 19:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0006_alter_placa_atividades_autorizadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subzona',
            name='geometria',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='zona',
            name='geometria',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
