# Generated by Django 5.0.6 on 2025-07-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0007_placa_max_pessoas_catamara_placa_max_pessoas_miudas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_code_value',
            field=models.UUIDField(blank=True, editable=False, help_text='Valor único para o QR Code físico.', null=True),
        ),
    ]
