# Generated by Django 5.0.6 on 2025-07-23 22:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placa',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='placa',
            name='embarcacoes',
        ),
        migrations.RemoveField(
            model_name='placa',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='placa',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='placa',
            name='subzona',
        ),
        migrations.RemoveField(
            model_name='placa',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='placa',
            name='atividades_permitidas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placa',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='placa',
            name='max_pessoas_catamara',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placa',
            name='max_pessoas_miudas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placa',
            name='num_embarcacoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placa',
            name='qtd_placas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placa',
            name='zona',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='placa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placa',
            name='localidade',
            field=models.CharField(max_length=255),
        ),
    ]
