# Generated by Django 5.0.6 on 2025-07-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0002_remove_placa_cor_remove_placa_embarcacoes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Placa',
        ),
    ]
