# Generated by Django 5.2.1 on 2025-07-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Placa",
        ),
    ]
