# Generated by Django 5.2 on 2025-04-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="role",
            field=models.CharField(
                choices=[
                    ("secretaria", "Secretaria"),
                    ("tbc", "TBC"),
                    ("turista", "Turista"),
                ],
                max_length=20,
            ),
        ),
    ]
