# Generated by Django 5.2 on 2025-04-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_usuario_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="role",
        ),
        migrations.AddField(
            model_name="usuario",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
