# Generated by Django 5.2 on 2025-04-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_usuario_role_usuario_bio"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="bio",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="usuario_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="usuario_set", to="auth.permission"
            ),
        ),
    ]
