# Generated by Django 5.2.1 on 2025-07-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_usuario_bio_alter_usuario_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Placa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_placa", models.CharField(max_length=255)),
                ("subzona", models.CharField(max_length=50)),
                ("localidade", models.CharField(max_length=100)),
                ("embarcacoes", models.IntegerField()),
                ("usuarios", models.IntegerField()),
                ("cor", models.CharField(max_length=7)),
                ("descricao", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
