# Generated by Django 5.0.6 on 2025-07-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceirob2b',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parceiro_b2b', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='produtosmarketplace',
            name='comunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='marketplace.comunidadelocal'),
        ),
        migrations.AddField(
            model_name='produtosmarketplace',
            name='parceiro_b2b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='marketplace.parceirob2b'),
        ),
        migrations.AddField(
            model_name='roteiropontointeresse',
            name='ponto_interesse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.pontodeinteresse'),
        ),
        migrations.AddField(
            model_name='roteiroturistico',
            name='comunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiros', to='marketplace.comunidadelocal'),
        ),
        migrations.AddField(
            model_name='roteiropontointeresse',
            name='roteiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.roteiroturistico'),
        ),
        migrations.AddField(
            model_name='transacaomarketplace',
            name='comprador_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='transacaomarketplace',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='marketplace.produtosmarketplace'),
        ),
        migrations.AlterUniqueTogether(
            name='roteiropontointeresse',
            unique_together={('roteiro', 'ponto_interesse')},
        ),
    ]
