# Generated by Django 5.0.6 on 2025-07-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0002_historicolocalizacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoLocalizacao',
        ),
    ]
