# Generated by Django 5.0.6 on 2025-07-29 05:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_perfil', models.CharField(default='Turista', max_length=50)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('pais_origem', models.CharField(choices=[('Argentina', 'Argentina'), ('Bolívia', 'Bolívia'), ('Brasil', 'Brasil'), ('Chile', 'Chile'), ('Colômbia', 'Colômbia'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('República Dominicana', 'República Dominicana'), ('Equador', 'Equador'), ('El Salvador', 'El Salvador'), ('Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('México', 'México'), ('Nicarágua', 'Nicarágua'), ('Panamá', 'Panamá'), ('Paraguai', 'Paraguai'), ('Peru', 'Peru'), ('Porto Rico', 'Porto Rico'), ('Uruguai', 'Uruguai'), ('Venezuela', 'Venezuela'), ('Estados Unidos', 'Estados Unidos'), ('Canadá', 'Canadá'), ('Portugal', 'Portugal'), ('Espanha', 'Espanha'), ('França', 'França'), ('Alemanha', 'Alemanha'), ('Reino Unido', 'Reino Unido'), ('Itália', 'Itália'), ('Japão', 'Japão'), ('China', 'China'), ('Austrália', 'Austrália'), ('Outro', 'Outro')], default='Brasil', max_length=255)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cidade')),
                ('estado_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuario_set', related_query_name='usuario', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_set', related_query_name='usuario', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
