# Generated by Django 5.0.6 on 2025-07-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_cidade_origem_usuario_estado_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pais_origem',
            field=models.CharField(choices=[('Brasil', 'Brasil'), ('Argentina', 'Argentina'), ('Estados Unidos', 'Estados Unidos'), ('Canadá', 'Canadá'), ('Portugal', 'Portugal'), ('Espanha', 'Espanha'), ('França', 'França'), ('Alemanha', 'Alemanha'), ('Reino Unido', 'Reino Unido'), ('Itália', 'Itália'), ('Japão', 'Japão'), ('China', 'China'), ('Austrália', 'Austrália'), ('Outro', 'Outro')], default='Brasil', max_length=255),
        ),
    ]
