# Generated by Django 5.0.6 on 2025-07-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_pais_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pais_origem',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Bolívia', 'Bolívia'), ('Brasil', 'Brasil'), ('Chile', 'Chile'), ('Colômbia', 'Colômbia'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('República Dominicana', 'República Dominicana'), ('Equador', 'Equador'), ('El Salvador', 'El Salvador'), ('Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('México', 'México'), ('Nicarágua', 'Nicarágua'), ('Panamá', 'Panamá'), ('Paraguai', 'Paraguai'), ('Peru', 'Peru'), ('Porto Rico', 'Porto Rico'), ('Uruguai', 'Uruguai'), ('Venezuela', 'Venezuela'), ('Outro', 'Outro')], default='Brasil', max_length=255),
        ),
    ]
