# Generated by Django 5.0.6 on 2025-07-27 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('usuarios', '0005_alter_usuario_pais_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cidade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cidade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado'),
        ),
    ]
